### ISSUE TITLE
numba.core.errors

### ISSUE THREAD

**Issue by gorliver** [odoluca/Fast-NW-and-SW-Pairwise-alignment-using-numba-JIT#2]
I got this warning when aligning two short sequences:
```
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of BoundFunction(list.append for list(unicode_type)<iv=None>) with parameters (Literal[int](-1))

During: resolving callee type: BoundFunction(list.append for list(unicode_type)<iv=None>)
During: typing of call at pairwise_JIT.py (526)


File "pairwise_JIT.py", line 526:
    def g(k):
        <source elided>
            al1.append(A[i])
            al2.append(-1)
            ^
```
I have test numba using the example from numba document and numba works well.

**Comment by odoluca** [comment]
Thank you for reporting. I will be working on it as soon as possible.

**Comment by odoluca** [comment]
I believe you have tried to align without numerizing the sequence. Because numba cannot work with strings, the values has to be numerized. I will update the documentation to avoid misguiding. Thank you

THE PROPER USE:

`a=convert_to_numeric("ATCTAGTCA")`
`b=convert_to_numeric("ATCTAGTCACGTAG")`
`localms_align(a,b,1,-1,-1,-2)`
(array([1, 0, 3, 0, 1, 2, 0, 3, 1], dtype=int64), array([1, 0, 3, 0, 1, 2, 0, 3, 1], dtype=int64), 9.0)

RECREATING THE ERROR:

`a="ATCTAGTCA"`
`b="ATCTAGTCACGTAG"`
`localms_align(a,b,1,-1,-1,-2)`
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Osman\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 482, in _compile_for_args
    error_rewrite(e, 'typing')
  File "C:\Users\Osman\AppData\Local\Programs\Python\Python38\lib\site-packages\numba\core\dispatcher.py", line 423, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of BoundFunction(list.append for list(unicode_type)<iv=None>) with parameters (Literal[int](-1))
During: resolving callee type: BoundFunction(list.append for list(unicode_type)<iv=None>)
During: typing of call at C:/Users/Osman/PycharmProjects/G4relation/pairwise_JIT.py (526)
File "pairwise_JIT.py", line 526:
    def g(k):
        <source elided>
            al1.append(A[i])
            al2.append(-1)
            ^

**Comment by gorliver** [comment]
Thank you very much for pointing out that!
